name: DEPLOY

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # with:
      #   ref: $GITHUB_REF # This should be the value set by the release event
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./ackfock
          remote_path: ./ackfock
          remote_host: ${{ secrets.HOST }}
          remote_user: ackfock
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
